---
- name: Install dependencies
  yum:
    name:
      - curl
      - gnupg
      - yum-utils
    state: present

- name: Add Kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el9-x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    state: present

#- name: Clean and update yum cache
#  shell: |
#    yum clean all
#    yum makecache fast

- name: Install Kubernetes components
  yum:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Ensure kubelet is enabled and started
  systemd:
    name: kubelet
    enabled: yes
    state: started
