---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - docker
    - k8s-all

- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  roles:
    - k8s-master

- name: Setup Kubernetes Workers
  hosts: workers
  become: yes
  roles:
    - k8s-worker
