---
- name: Remove conflicting curl-minimal package
  yum:
    name: curl-minimal
    state: absent
  ignore_errors: yes  # Ignora caso o pacote não esteja presente

- name: Install curl (full version)
  yum:
    name: curl
    state: present

- name: Install Docker dependencies
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Install Docker from Amazon Linux repository
  yum:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Enable Docker to start on boot
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add the user to the docker group
  user:
    name: "ec2-user"
    group: docker
    append: yes

- name: Ensure the docker.sock permissions are correct
  file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0660'

- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: yes
  become: true

- name: Restart Docker to apply group changes
  systemd:
    name: docker
    state: restarted
