---
- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.10.0.0/16
  become: yes
  register: kubeadm_init
  ignore_errors: yes

- name: Copy kubeconfig to user home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ec2-user/.kube/config  # Ajustado para o usuário padrão do Amazon Linux 2
    remote_src: yes
    owner: ec2-user  # Ajustado para o usuário padrão do Amazon Linux 2
    group: ec2-user  # Ajustado para o usuário padrão do Amazon Linux 2
    mode: '0644'

- name: Create .kube directory for the user if it doesn't exist
  file:
    path: /home/ec2-user/.kube
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Get the kubeadm join command
  debug:
    var: kubeadm_init.stdout_lines
  when: kubeadm_init.stdout_lines is defined
